[build-system]
requires = ["setuptools", "wheel"]

[tool.pytest.ini_options]
addopts = "--strict-markers -vv"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
testpaths = [
    "tests",
]

[tool.black]
line-length = 120
